### ISSUE TITLE
@ckeditor/ckeditor5-watchdog latest update issue

### ISSUE THREAD

**Issue by Nightcro** [ckeditor/ckeditor5-angular#356]
Hello, after updating to latest version, I get this error. I do not have @ckeditor/ckeditor5-watchdog in my package.json.

Error: node_modules/@ckeditor/ckeditor5-angular/ckeditor.component.d.ts:7:28 - error TS7016: Could not find a declaration file for module '@ckeditor/ckeditor5-watchdog/src/watchdog'. /node_modules/@ckeditor/ckeditor5-angular/node_modules/@ckeditor/ckeditor5-watchdog/src/watchdog.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ckeditor__ckeditor5-watchdog` if it exists or add a new declaration (.d.ts) file containing `declare module '@ckeditor/ckeditor5-watchdog/src/watchdog';`

7 import WatchdogConfig from '@ckeditor/ckeditor5-watchdog/src/watchdog';

**Comment by Nightcro** [comment]
Managed to fix by adding

`declare module '@ckeditor/ckeditor5-watchdog/src/watchdog' {
	const WatchdogConfig: any;
	type WatchdogConfig = any;

	export default WatchdogConfig;
}`

**Comment by Nightcro** [comment]
I managed to fix it by adding this:

```typescript
declare module '@ckeditor/ckeditor5-watchdog/src/watchdog' {
	const WatchdogConfig: any;
	type WatchdogConfig = any;
        export default WatchdogConfig;
}
```

**Comment by mabryl** [comment]
Hi @Nightcro,

Thanks for reaching out. Looks like the issue is reproducible, so thank you for bringing it to our attention.

Precise steps on how to reproduce with a fresh Angular app:

1. Create a new Angular project: `ng new angular-ckeditor`
2. Install the CKEditor Angular component: `npm install --save @ckeditor/ckeditor5-angular`
3. Install the CKE build of your choice, e.g. Classic: `npm install --save @ckeditor/ckeditor5-build-classic`
4. Create the `typings.d.ts` file in accordance with [our docs](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html#strict-mode-project-tips)
5. Try to build the app: `ng build`
6. This error appears:
```
Error: node_modules/@ckeditor/ckeditor5-angular/ckeditor.component.d.ts:7:28 - error TS7016: Could not find a declaration file for module '@ckeditor/ckeditor5-watchdog/src/watchdog'. '[...]/node_modules/@ckeditor/ckeditor5-watchdog/src/watchdog.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ckeditor__ckeditor5-watchdog` if it exists or add a new declaration (.d.ts) file containing `declare module '@ckeditor/ckeditor5-watchdog/src/watchdog';`

7 import WatchdogConfig from '@ckeditor/ckeditor5-watchdog/src/watchdog';
```

Running `npm i --save-dev @types/ckeditor__ckeditor5-watchdog`, as suggested by the error message fixes the issue and lets you build the app.

@pomek let me know if you want me to retest this.

**Comment by pomek** [comment]
Ok, so as long as CKEditor 5 Angular component uses the Watchdog feature from the JS version of the code, we must include typings as a dependency too.

Thanks @mabryl, for confirming the issue. We will let you know once we release the solution. I hope it will next week.

**Comment by rbalet** [comment]
@Nightcro I do get the following error while trying your fix.

```
annot redeclare exported variable 'default'.ts(2323)
type WatchdogConfig = any
const WatchdogConfig: any
```

Where did you have added this piece of code ?

**Comment by Nightcro** [comment]
This was fixed with the latest release of ckeditor, you do not need these typings anymore.
Follow the update guide from ckeditor for latest release

[https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-37.html](https://ckeditor.com/docs/ckeditor5/latest/updating/guides/update-to-37.html)

I will close this issue

**Comment by rbalet** [comment]
Thx @Nightcro, I still have the error though, I did a add a [pull request](https://github.com/ckeditor/ckeditor5-angular/pull/365) that helped me solve the problem
